name: api
services:
  db:
    image: postgres:17.6
    container_name: db
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - api-network
    restart: always
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy

networks:
  api-network:
    driver: bridge
